<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>$(AtomUIDevelopTargetFramework)</TargetFramework>
        <Nullable>enable</Nullable>
        <RootNamespace>AtomUILabsGallery</RootNamespace>
        <AssemblyName>AtomUILabsGallery</AssemblyName>
    </PropertyGroup>

    <ItemGroup>
        <AssemblyMetadata Include="AtomUIVersion" Value="$(AtomUIVersion)"/>
        <AssemblyMetadata Include="AtomUILabsVersion" Value="$(AtomUILabsVersion)"/>
    </ItemGroup>

    <ItemGroup>
        <AvaloniaResource Include="../../resources/images/atomui-labs.png" Link="Assets/atomui-labs.png"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia"/>
        <PackageReference Include="AtomUI.Desktop.Controls"/>
        <PackageReference Include="AtomUI.Toolkits.GalleryBase"/>
        <PackageReference Include="AtomUI.Generator" PrivateAssets="all"/>
        <PackageReference Include="ReactiveUI.Avalonia"/>
        <PackageReference Condition="'$(Configuration)' == 'Debug'" Include="AvaloniaUI.DiagnosticsSupport"/>
    </ItemGroup>
</Project>
